import Head from "next/head";

import { Heading } from "../components/Heading";
import { PanelLayout } from "../layouts/PanelLayout";
import { Text } from "../components/Text";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PanelLayout>
        <Heading className="text-2xl font-bold mb-2">Happening now</Heading>
        <Text className="font-bold mb-8">Join Twitter today</Text>
      </PanelLayout>
    </>
  );
};

export default Home;
